### ISSUE TITLE
Does not work with new CoFHCore-[1.7.10]3.0.0B5-30

### ISSUE THREAD

**Issue by Tsunayoshi** [erogenousbeef/BigReactors#307]
Version: BigReactors-0.4.0rc3

Libs:
CoFHCore-[1.7.10]3.0.0B5-30
CoFHLib-[1.7.10]1.0.0B4-24

TE/MF Versions:
ThermalExpansion-[1.7.10]4.0.0B5-13
ThermalFoundation-[1.7.10]1.0.0B3-8
MineFactoryReloaded-[1.7.10]2.8.0RC2-557
(RedstoneArsenal-[1.7.10]1.1.0B4-10)

I updated all my files today and my client won't start with the newest CoFH Files. My previous version was CoFHCore-[1.7.10]3.0.0B3-26 and runs fine.

---- Minecraft Crash Report ----
// This is a token for 1 free hug. Redeem at your nearest Mojangsta: [~~HUG~~]

Time: 24.08.14 13:42
Description: There was a severe problem during mod loading that has caused the game to fail

cpw.mods.fml.common.LoaderException: java.lang.NoClassDefFoundError: cofh/util/ThermalExpansionHelper
    at cpw.mods.fml.common.LoadController.transition(LoadController.java:162)
    at cpw.mods.fml.common.Loader.initializeMods(Loader.java:692)
    at cpw.mods.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:288)
    at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:541)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:867)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:134)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.NoClassDefFoundError: cofh/util/ThermalExpansionHelper
    at erogenousbeef.bigreactors.common.CommonProxy.sendInterModAPIMessages(CommonProxy.java:72)
    at erogenousbeef.bigreactors.common.CommonProxy.init(CommonProxy.java:41)
    at erogenousbeef.bigreactors.client.ClientProxy.init(ClientProxy.java:41)
    at erogenousbeef.bigreactors.common.BRLoader.load(BRLoader.java:72)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:513)
    at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:208)
    at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:187)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:118)
    at cpw.mods.fml.common.Loader.initializeMods(Loader.java:691)
    ... 10 more
Caused by: java.lang.ClassNotFoundException: cofh.util.ThermalExpansionHelper
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:188)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    ... 40 more
Caused by: java.lang.NullPointerException
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- System Details --
Details:
    Minecraft Version: 1.7.10
    Operating System: Windows 7 (amd64) version 6.1
    Java Version: 1.7.0_60, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 1328285032 bytes (1266 MB) / 2505572352 bytes (2389 MB) up to 3817865216 bytes (3641 MB)
    JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4096m -XX:MaxPermSize=256m
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    FML: MCP v9.05 FML v7.10.25.1208 Minecraft Forge 10.13.0.1208 133 mods loaded, 133 mods active
    mcp{9.05} [Minecraft Coder Pack](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized
    FML{7.10.25.1208} [Forge Mod Loader](modpack.jar) Unloaded->Constructed->Pre-initialized->Initialized
    Forge{10.13.0.1208} [Minecraft Forge](modpack.jar) Unloaded->Constructed->Pre-initialized->Initialized
    AppliedEnergistics2-Core{rv0-stable-10} [AppliedEnergistics2 Core](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized
    CodeChickenCore{1.0.3.23} [CodeChicken Core](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized
    <CoFH ASM>{000} [CoFH ASM Data Initialization](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized
    MCVanillaTweaks{1.0} [Mariculture - Vanilla Tweaks](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized
    Micdoodlecore{} [Micdoodle8 Core](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized
    NotEnoughItems{1.0.3.51} [Not Enough Items](NotEnoughItems-1.7.10-1.0.3.51-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized
    OpenEye{0.6} [OpenEye](OpenEye-0.6-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized
    TConstruct-Preloader{0.1.1} [Tinkers Corestruct](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized
    ThaumicTinkerer-preloader{0.1} [Thaumic Tinkerer Core](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized
    OpenModsCore{@VERSION@} [OpenModsCore](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized
    lucky{5.1.0} [Lucky Block]([1-7-10]_Lucky_Block_v5-1-0.jar.zip) Unloaded->Constructed->Pre-initialized->Initialized
    IC2{2.2.617-experimental} [IndustrialCraft 2](industrialcraft-2-2.2.617-experimental.jar) Unloaded->Constructed->Pre-initialized->Initialized
    AdvancedMachines{1.1.2} [IC2 Advanced Machines Addon](AdvancedMachinesAS-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized
    CoFHCore{1.7.10R3.0.0B5} [CoFH Core](CoFHCore-[1.7.10]3.0.0B5-30.jar) Unloaded->Constructed->Pre-initialized->Initialized
    ThermalFoundation{1.7.10R1.0.0B3} [Thermal Foundation](ThermalFoundation-[1.7.10]1.0.0B3-8.jar) Unloaded->Constructed->Pre-initialized->Initialized
    ThermalExpansion{1.7.10R4.0.0B5} [Thermal Expansion](ThermalExpansion-[1.7.10]4.0.0B5-13.jar) Unloaded->Constructed->Pre-initialized->Initialized
    appliedenergistics2{rv0-stable-10} [Applied Energistics 2](appliedenergistics2-rv0-stable-10.jar) Unloaded->Constructed->Pre-initialized->Initialized
    bdlib{1.4.2.9} [BD Lib](bdlib-mc1710-1.4.2.9.jar) Unloaded->Constructed->Pre-initialized->Initialized
    BiblioCraft{1.7.5} [BiblioCraft](BiblioCraft[v1.7.5][MC1.7.10].jar) Unloaded->Constructed->Pre-initialized->Initialized
    Mantle{1.7.10-165.4bc3343} [Mantle](Mantle_mc1.7.10_0.3.0.jar) Unloaded->Constructed->Pre-initialized->Initialized
    Natura{2.2.0} [Natura](natura-1.7.10-2.2.0-b1.jar) Unloaded->Constructed->Pre-initialized->Initialized
    BiomesOPlenty{2.1.0} [Biomes O' Plenty](BiomesOPlenty-1.7.10-2.1.0.977-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized
    BiblioWoodsBoP{1.7} [BiblioWoods Biomes O'Plenty Edition](BiblioWoods[BiomesOPlenty][v1.7].jar) Unloaded->Constructed->Pre-initialized->Initialized
    Forestry{3.0.0.90} [Forestry for Minecraft](forestry_1.7.10-3.0.0.90.jar) Unloaded->Constructed->Pre-initialized->Initialized
    BiblioWoodsForestry{1.5} [BiblioWoods Forestry Edition](BiblioWoods[Forestry][v1.5].jar) Unloaded->Constructed->Pre-initialized->Initialized
    BiblioWoodsNatura{1.3} [BiblioWoods Natura Edition](BiblioWoods[Natura][v1.3].jar) Unloaded->Constructed->Pre-initialized->Initialized
    BigReactors{0.4.0rc3} [Big Reactors](BigReactors-0.4.0rc3.jar) Unloaded->Constructed->Pre-initialized->Errored
    BinnieCore{2.0-dev3} [Binnie Core](binnie-mods-2.0-dev3.jar) Unloaded->Constructed->Pre-initialized->Initialized
    Botany{2.0-dev3} [Botany](binnie-mods-2.0-dev3.jar) Unloaded->Constructed->Pre-initialized->Initialized
    ExtraBees{2.0-dev3} [Extra Bees](binnie-mods-2.0-dev3.jar) Unloaded->Constructed->Pre-initialized->Initialized
    ExtraTrees{2.0-dev3} [Extra Trees](binnie-mods-2.0-dev3.jar) Unloaded->Constructed->Pre-initialized->Initialized
    Genetics{2.0-dev3} [Genetics](binnie-mods-2.0-dev3.jar) Unloaded->Constructed->Pre-initialized->Initialized
    AWWayofTime{v1.0.1g} [Blood Magic: Alchemical Wizardry](Blood Magic-v1.1.0%281.7.10%29.jar) Unloaded->Constructed->Pre-initialized->Initialized
    Baubles{1.0.1.5} [Baubles](Baubles-1.7.10-1.0.1.5.jar) Unloaded->Constructed->Pre-initialized->Initialized
    Thaumcraft{4.2.0.0} [Thaumcraft](Thaumcraft-1.7.10-4.2.0.0.jar) Unloaded->Constructed->Pre-initialized->Initialized
    Botania{r1.2-102} [Botania](Botania r1.2-102.jar) Unloaded->Constructed->Pre-initialized->Initialized
    CarpentersBlocks{3.2.5} [Carpenter's Blocks](Carpenter's Blocks v3.2.6 - MC 1.7.10.zip) Unloaded->Constructed->Pre-initialized->Initialized
    chisel{1.5.6b} [Chisel](Chisel-1.7.10-1.5.6b.jar) Unloaded->Constructed->Pre-initialized->Initialized
    cookiecore{1.2.0} [Cookie Core](cookiecore-1.2.0.jar) Unloaded->Constructed->Pre-initialized->Initialized
    DynamicLights{1.3.5} [Dynamic Lights](DynamicLights-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized
    DynamicLights_onFire{1.0.4} [Dynamic Lights Burning Entity Module](DynamicLights-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized
    DynamicLights_creepers{1.0.4} [Dynamic Lights Creeper Module](DynamicLights-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized
    DynamicLights_dropItems{1.0.7} [Dynamic Lights EntityItem Module](DynamicLights-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized
    DynamicLights_entityClasses{1.0.1} [Dynamic Lights Entity Light Module](DynamicLights-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized
    DynamicLights_mobEquipment{1.0.5} [Dynamic Lights Mob Equipment Light Module](DynamicLights-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized
    DynamicLights_flameArrows{1.0.0} [Dynamic Lights Fiery Arrows Light Module](DynamicLights-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized
    DynamicLights_floodLights{1.0.1} [Dynamic Lights Flood Light](DynamicLights-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized
    DynamicLights_otherPlayers{1.0.7} [Dynamic Lights OtherPlayers Light Module](DynamicLights-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized
    DynamicLights_thePlayer{1.1.3} [Dynamic Lights Player Light Module](DynamicLights-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized
    Enchiridion{1.1} [Enchiridion](Enchiridion-1.7.X-1.2b.jar) Unloaded->Constructed->Pre-initialized->Initialized
    EnderIO{1.7.10-2.0.0.191} [Ender IO](EnderIO-1.7.10-2.0.0.191.jar) Unloaded->Constructed->Pre-initialized->Initialized
    EnderStorage{1.4.5.20} [EnderStorage](EnderStorage-1.7.10-1.4.5.20-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized
    Waila{1.5.3} [Waila](Waila-1.5.3_1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized
    extracells{2.1.3} [ExtraCells](ExtraCells-2.1.3.jar) Unloaded->Constructed->Pre-initialized->Initialized
    UniversalElectricity{@MAJOR@.@MINOR@.@REVIS@} [Universal Electricity](universal-electricity-4.0.0.50-core.jar) Unloaded->Constructed->Pre-initialized->Initialized
    ForgeMultipart{1.1.0.296} [Forge Multipart](ForgeMultipart-1.7.10-1.1.0.296-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized
    ExtraUtilities{1.1.0f} [Extra Utilities](extrautilities-1.1.0f.jar) Unloaded->Constructed->Pre-initialized->Initialized
    factorization.notify{1.0} [Factorization Notification System](Factorization-1.7.10-0.8.87.1.jar) Unloaded->Constructed->Pre-initialized->Initialized
    factorization{1.7.10-0.8.87.1} [Factorization](Factorization-1.7.10-0.8.87.1.jar) Unloaded->Constructed->Pre-initialized->Initialized
    factorization.misc{1.7.10-0.8.87.1} [Factorization Miscellaneous Nonsense](Factorization-1.7.10-0.8.87.1.jar) Unloaded->Constructed->Pre-initialized->Initialized
    GalacticraftCore{3.0.1} [Galacticraft Core](GalacticraftCore-BETA-1.7-3.0.1.170.jar) Unloaded->Constructed->Pre-initialized->Initialized
    GalacticraftMars{3.0.1} [Galacticraft Planets](Galacticraft-Planets-BETA-1.7-3.0.1.170.jar) Unloaded->Constructed->Pre-initialized->Initialized
    MineFactoryReloaded{1.7.10R2.8.0RC2} [MineFactory Reloaded](MineFactoryReloaded-[1.7.10]2.8.0RC2-557.jar) Unloaded->Constructed->Pre-initialized->Initialized
    gendustry{1.3.1.12} [GenDustry](gendustry-mc1710-1.3.1.12.jar) Unloaded->Constructed->Pre-initialized->Initialized
    HardcoreQuesting{The Journey (4.2.0)} [Hardcore Questing Mode](HQM-The Journey %284.2.0%29.jar) Unloaded->Constructed->Pre-initialized->Initialized
    iChunUtil{4.0.0} [iChunUtil](iChunUtil-4.0.0.jar) Unloaded->Constructed->Pre-initialized->Initialized
    InfernalMobs{1.5.6} [Infernal Mobs](InfernalMobs-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized
    inventorytweaks{1.59-dev-152-cf6e263} [Inventory Tweaks](InventoryTweaks-1.59-dev-152.jar) Unloaded->Constructed->Pre-initialized->Initialized
    IronChest{6.0.49.733} [Iron Chest](ironchest-1.7.10-6.0.49.733-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized
    JABBA{1.1.4} [JABBA](Jabba-1.1.4_1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized
    lloverlay{@VERSION@} [Light Level Overlay](lloverlay-0.23a-10.12.0.1007-forge.jar.zip) Unloaded->Constructed->Pre-initialized->Initialized
    Railcraft{9.2.2.0} [Railcraft](Railcraft_1.7.10-9.2.2.0.jar) Unloaded->Constructed->Pre-initialized->Initialized
    TConstruct{1.7.10-1.6.0.build591} [Tinkers' Construct](TConstruct_mc1.7.10_1.6.0d39.jar) Unloaded->Constructed->Pre-initialized->Initialized
    ThaumicTinkerer{2.5-1.7.10-153} [Thaumic Tinkerer](ThaumicTinkerer-2.5-1.7.10-153.jar) Unloaded->Constructed->Pre-initialized->Initialized
    MagicBees{1.7.10-2.1.19} [Magic Bees](magicbees-1.7.10-2.1.19.jar) Unloaded->Constructed->Pre-initialized->Initialized
    MapWriter{2.1.2} [MapWriter](MapWriter-1.7.10-2.1.2.jar) Unloaded->Constructed->Pre-initialized->Initialized
    Mariculture{1.2.3b} [Mariculture](Mariculture-1.7.10-1.2.3b.jar) Unloaded->Constructed->Pre-initialized->Initialized
    ResonantEngine{@MAJOR@.@MINOR@.@REVIS@} [Resonant Engine](resonant-engine-2.0.0.82-core.jar) Unloaded->Constructed->Pre-initialized->Initialized
    MFFS{@MAJOR@.@MINOR@.@REVIS@} [Modular Force Field System](mffs-4.1.0.23-core.jar) Unloaded->Constructed->Pre-initialized->Initialized
    MineFactoryReloaded|CompatAppliedEnergistics{1.7.10R2.8.0RC2} [MFR Compat: Applied Energistics](MineFactoryReloaded-[1.7.10]2.8.0RC2-557.jar) Unloaded->Constructed->Pre-initialized->Initialized
    MineFactoryReloaded|CompatAtum{1.7.10R2.8.0RC2} [MFR Compat: Atum](MineFactoryReloaded-[1.7.10]2.8.0RC2-557.jar) Unloaded->Constructed->Pre-initialized->Initialized
    MineFactoryReloaded|CompatBackTools{1.7.10R2.8.0RC2} [MFR Compat: BackTools](MineFactoryReloaded-[1.7.10]2.8.0RC2-557.jar) Unloaded->Constructed->Pre-initialized->Initialized
    MineFactoryReloaded|CompatBuildCraft{1.7.10R2.8.0RC2} [MFR Compat: BuildCraft](MineFactoryReloaded-[1.7.10]2.8.0RC2-557.jar) Unloaded->Constructed->Pre-initialized->Initialized
    MineFactoryReloaded|CompatChococraft{1.7.10R2.8.0RC2} [MFR Compat: Chococraft](MineFactoryReloaded-[1.7.10]2.8.0RC2-557.jar) Unloaded->Constructed->Pre-initialized->Initialized
    MineFactoryReloaded|CompatExtraBiomes{1.7.10R2.8.0RC2} [MFR Compat: ExtraBiomes](MineFactoryReloaded-[1.7.10]2.8.0RC2-557.jar) Unloaded->Constructed->Pre-initialized->Initialized
    MineFactoryReloaded|CompatForestry{1.7.10R2.8.0RC2} [MFR Compat: Forestry](MineFactoryReloaded-[1.7.10]2.8.0RC2-557.jar) Unloaded->Constructed->Pre-initialized->Initialized
    MineFactoryReloaded|CompatForgeMicroblock{1.7.10R2.8.0RC2} [MFR Compat: ForgeMicroblock](MineFactoryReloaded-[1.7.10]2.8.0RC2-557.jar) Unloaded->Constructed->Pre-initialized->Initialized
    MineFactoryReloaded|CompatIC2{1.7.10R2.8.0RC2} [MFR Compat: IC2](MineFactoryReloaded-[1.7.10]2.8.0RC2-557.jar) Unloaded->Constructed->Pre-initialized->Initialized
    Mystcraft{0.10.15.00} [Mystcraft](mystcraft-1.7.2-0.10.15.00.jar) Unloaded->Constructed->Pre-initialized->Initialized
    MineFactoryReloaded|CompatMystcraft{1.7.10R2.8.0RC2} [MFR Compat: Mystcraft](MineFactoryReloaded-[1.7.10]2.8.0RC2-557.jar) Unloaded->Constructed->Pre-initialized->Initialized
    MineFactoryReloaded|CompatPams{1.7.10R2.8.0RC2} [MFR Compat: Pam's Mods](MineFactoryReloaded-[1.7.10]2.8.0RC2-557.jar) Unloaded->Constructed->Pre-initialized->Initialized
    ProjRed|Core{4.4.5.44} [ProjectRed](ProjectRed-Base-1.7.10-4.4.5.44.jar) Unloaded->Constructed->Pre-initialized->Initialized
    ProjRed|Exploration{4.4.5.44} [ProjectRed-Exploration](ProjectRed-World-1.7.10-4.4.5.44.jar) Unloaded->Constructed->Pre-initialized->Initialized
    MineFactoryReloaded|CompatProjRed{1.7.10R2.8.0RC2} [MFR Compat ProjectRed](MineFactoryReloaded-[1.7.10]2.8.0RC2-557.jar) Unloaded->Constructed->Pre-initialized->Initialized
    MineFactoryReloaded|CompatRailcraft{1.7.10R2.8.0RC2} [MFR Compat: Railcraft](MineFactoryReloaded-[1.7.10]2.8.0RC2-557.jar) Unloaded->Constructed->Pre-initialized->Initialized
    MineFactoryReloaded|CompatRP2{1.7.10R2.8.0RC2} [MFR Compat: RP2](MineFactoryReloaded-[1.7.10]2.8.0RC2-557.jar) Unloaded->Constructed->Pre-initialized->Initialized
    MineFactoryReloaded|CompatSufficientBiomes{1.7.10R2.8.0RC2} [MFR Compat: Sufficient Biomes](MineFactoryReloaded-[1.7.10]2.8.0RC2-557.jar) Unloaded->Constructed->Pre-initialized->Initialized
    MineFactoryReloaded|CompatThaumcraft{1.7.10R2.8.0RC2} [MFR Compat: Thaumcraft](MineFactoryReloaded-[1.7.10]2.8.0RC2-557.jar) Unloaded->Constructed->Pre-initialized->Initialized
    MineFactoryReloaded|CompatThermalExpansion{1.7.10R2.8.0RC2} [MFR Compat: Thermal Expansion](MineFactoryReloaded-[1.7.10]2.8.0RC2-557.jar) Unloaded->Constructed->Pre-initialized->Initialized
    MineFactoryReloaded|CompatTwilightForest{1.7.10R2.8.0RC2} [MFR Compat: TwilightForest](MineFactoryReloaded-[1.7.10]2.8.0RC2-557.jar) Unloaded->Constructed->Pre-initialized->Initialized
    MineFactoryReloaded|CompatVanilla{1.7.10R2.8.0RC2} [MFR Compat: Vanilla](MineFactoryReloaded-[1.7.10]2.8.0RC2-557.jar) Unloaded->Constructed->Pre-initialized->Initialized
    Morph{0.9.0} [Morph](Morph-Beta-0.9.0.jar) Unloaded->Constructed->Pre-initialized->Initialized
    Morpheus{1.7.10-1.5.18} [Morpheus](Morpheus-1.7.10-1.5.18.jar) Unloaded->Constructed->Pre-initialized->Initialized
    NEIAddons{1.12.1.8} [NEI Addons](neiaddons-mc1710-1.12.1.8.jar) Unloaded->Constructed->Pre-initialized->Initialized
    NEIAddons|Botany{1.12.1.8} [NEI Addons: Botany](neiaddons-mc1710-1.12.1.8.jar) Unloaded->Constructed->Pre-initialized->Initialized
    NEIAddons|Forestry{1.12.1.8} [NEI Addons: Forestry](neiaddons-mc1710-1.12.1.8.jar) Unloaded->Constructed->Pre-initialized->Initialized
    NEIAddons|CraftingTables{1.12.1.8} [NEI Addons: Crafting Tables](neiaddons-mc1710-1.12.1.8.jar) Unloaded->Constructed->Pre-initialized->Initialized
    NEIAddons|ExNihilo{1.12.1.8} [NEI Addons: Ex Nihilo](neiaddons-mc1710-1.12.1.8.jar) Unloaded->Constructed->Pre-initialized->Initialized
    NetherOres{1.7.10R2.3.0RC3} [Nether Ores](NetherOres-[1.7.10]2.3.0RC3-84.jar) Unloaded->Constructed->Pre-initialized->Initialized
    OpenMods{0.6} [OpenMods](OpenModsLib-1.7.10-0.6-snapshot-223.jar) Unloaded->Constructed->Pre-initialized->Initialized
    OpenBlocks{1.3} [OpenBlocks](OpenBlocks-1.7.10-1.3-snapshot-432.jar) Unloaded->Constructed->Pre-initialized->Initialized
    harvestcraft{1.7.2d} [Pam's HarvestCraft](Pam's HarvestCraft 1.7.10a.zip) Unloaded->Constructed->Pre-initialized->Initialized
    PneumaticCraft{1.2.5} [PneumaticCraft](PneumaticCraft-1.2.5.jar) Unloaded->Constructed->Pre-initialized->Initialized
    ProjRed|Transmission{4.4.5.44} [ProjectRed-Transmission](ProjectRed-Integration-1.7.10-4.4.5.44.jar) Unloaded->Constructed->Pre-initialized->Initialized
    ProjRed|Transportation{4.4.5.44} [ProjectRed-Transportation](ProjectRed-Mechanical-1.7.10-4.4.5.44.jar) Unloaded->Constructed->Pre-initialized->Initialized
    ProjRed|Compatibility{4.4.5.44} [ProjectRed-Compatibility](ProjectRed-Compat-1.7.10-4.4.5.44.jar) Unloaded->Constructed->Pre-initialized->Initialized
    ProjRed|Integration{4.4.5.44} [ProjectRed-Integration](ProjectRed-Integration-1.7.10-4.4.5.44.jar) Unloaded->Constructed->Pre-initialized->Initialized
    ProjRed|Illumination{4.4.5.44} [ProjectRed-Illumination](ProjectRed-Lighting-1.7.10-4.4.5.44.jar) Unloaded->Constructed->Pre-initialized->Initialized
    ProjRed|Expansion{4.4.5.44} [ProjectRed-Expansion](ProjectRed-Mechanical-1.7.10-4.4.5.44.jar) Unloaded->Constructed->Pre-initialized->Initialized
    RedstoneArsenal{1.7.10R1.1.0B4} [Redstone Arsenal](RedstoneArsenal-[1.7.10]1.1.0B4-10.jar) Unloaded->Constructed->Pre-initialized->Initialized
    TSteelworks{1.7.10-1.0.0} [Tinkers' Steelworks](TSteelworks-1.7.10-1.0.0.jar) Unloaded->Constructed->Pre-initialized->Initialized
    TiCTooltips{1.1.9} [TiC Tooltips](TiC-Tooltips-mc1.7.10-1.1.9.jar) Unloaded->Constructed->Pre-initialized->Initialized
    TMechworks{1.7.10-67.34d1d9b} [Tinkers' Mechworks](TMechworks_mc1.7.10_0.2.8.jar) Unloaded->Constructed->Pre-initialized->Initialized
    Translocator{1.1.1.9} [Translocator](Translocator-1.7.10-1.1.1.9-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized
    AS_UpdateCheck{1.1.6} [AtomicStryker Update Check Mod](UpdateCheckerMod-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized
    WailaHarvestability{1.0.4} [Waila Harvestability](WailaHarvestability-mc1.7.x-1.0.4.jar) Unloaded->Constructed->Pre-initialized->Initialized
    witchery{0.20.5} [Witchery](witchery-1.7.10-0.20.5.jar) Unloaded->Constructed->Pre-initialized->Initialized
    McMultipart{1.1.0.296} [Minecraft Multipart Plugin](ForgeMultipart-1.7.10-1.1.0.296-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized
    IguanaTweaksTConstruct{1.7.10-2.0.1.DEV.84b0c6f} [Iguana Tweaks for Tinkers Construct](IguanaTinkerTweaks-1.7.10-2.0.1B2.jar) Unloaded->Constructed->Pre-initialized->Initialized
    ForgeMicroblock{1.1.0.296} [Forge Microblocks](ForgeMultipart-1.7.10-1.1.0.296-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized
    AE2 Version: stable rv0-stable-10 for Forge 10.13.0.1152
    Mantle Environment: Environment healthy.
    TConstruct Environment: Environment healthy.
